name: Build Jemalloc Java Images
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
  push:

jobs:
  push:
    name: "pterodactyl-images:bookworm-jemalloc-java-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        tag:
          - 17-jre
          - 17-jdk
    steps:
      - uses: actions/checkout@v4
      - name: Generate Dockerfile
        working-directory: ./java
        run: ./gendocker.sh ${{ matrix.tag }}
        shell: bash
      - uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: ./java/build
          file: ./java/build/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ampflower/pterodactyl-java:bookworm-jemalloc-${{ matrix.tag }}